#!/usr/bin/env python3
"""Regenerate reports/results.md from committed artefacts only.

Reads: results/tables/*.csv, results/provenance/*.json,
calculations/*/relax_*/result.json ... and rewrites results.md.
Never invents numbers: missing data renders as 'n/a'.
"""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from mct_dft.detector import hansen_eg, cutoff_wavelength_um  # noqa: E402


def _f(x, fmt="{:.5f}"):
    return fmt.format(x) if isinstance(x, (int, float)) else "n/a"


def conv_table(system: str, kind: str) -> str:
    p = ROOT / "results/tables" / f"{system}_{kind}_convergence.csv"
    if not p.exists():
        return f"_no {kind} convergence table yet_\n"
    rows = list(csv.DictReader(open(p)))
    heads = [k for k in rows[0] if k not in ("wall_s", "ok")]
    out = ["| " + " | ".join(heads) + " |",
           "|" + "---|" * len(heads)]
    for r in rows:
        out.append("| " + " | ".join(str(r[h])[:14] for h in heads) + " |")
    return "\n".join(out) + "\n"


def band_table(system: str) -> str:
    res = {}
    for tag, lat in (("soc", None),):
        pass
    lines = []
    for tag in ("nosoc", "soc"):
        rj = ROOT / "calculations" / system / f"production_bands_{tag}" / "result.json"
        if not rj.exists():
            continue
        # recompute edges deterministically here (bands.npz)
        import numpy as np
        z = np.load(str(rj.parent / "bands.npz"))
        from mct_dft.bands import band_edges, n_valence_from_electrons
        import re as _re
        bres = json.loads(rj.read_text())
        ef = bres["pw"]["highest_occupied_ev"] or \
            bres.get("charge_reference_occupancy_ev")
        scf_out = (ROOT / "calculations" / system /
                   f"production_scf_{tag}" / "pw.out")
        nv = None
        if scf_out.exists():
            m = _re.search(r"number of electrons\s*=\s*([\d.]+)",
                           scf_out.read_text(errors="replace"))
            if m:
                nv = n_valence_from_electrons(float(m.group(1)),
                                              tag == "soc")
        ed = band_edges(z["kpts"], z["eigs_ev"], reference_ev=ef,
                        n_valence=nv)
        rr = json.loads((ROOT / "calculations" / system /
                         f"relax_{tag}" / "result.json").read_text())
        import numpy as _np
        cell = _np.asarray(rr["pw"]["final_cell_ang"], float)
        a = float(_np.linalg.norm(cell[0]) * _np.sqrt(2))
        lines.append(
            f"| {tag} | {a:.5f} | {ed.vbm_ev:.4f} | {ed.cbm_ev:.4f} "
            f"| {ed.gap_ev:.4f} | {ed.status} |"
        )
    if not lines:
        return "_bands not yet available_\n"
    return ("| treatment | a (A) | VBM (eV) | CBM (eV) | gap (eV) | status |\n"
            "|---|---|---|---|---|---|\n") + "\n".join(lines) + "\n"


def empirical_block(x: float) -> str:
    lines = ["| T (K) | Eg empirical (eV) | lambda_c (um) |",
             "|---|---|---|"]
    for T in (0.0, 77.0, 300.0):
        eg = hansen_eg(x, T)
        lam = cutoff_wavelength_um(eg)
        lines.append(f"| {T:.0f} | {eg:.6f} | "
                     f"{f'{lam:.5f}' if lam else 'n/a'} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    env = json.loads((ROOT / "results/provenance/environment.json").read_text())
    md = []
    md.append("# Results (auto-generated by scripts/update_reports.py)\n")
    md.append("Every DFT number below was parsed from raw QE output under "
              "`calculations/`; nothing was transcribed by hand. Regenerate "
              "with `python scripts/update_reports.py`.\n")

    md.append("\n## Environment\n")
    md.append("```json\n" + json.dumps(env, indent=1)[:1500] + "\n```\n")

    md.append("\n## Empirical benchmark (Hansen) — NOT DFT\n")
    md.append("x = 0.200:\n" + empirical_block(0.2))
    md.append("x = 0.199:\n" + empirical_block(0.199))
    md.append("> Static-lattice DFT is compared against the **T = 0 K** row "
              "only; 77 K / 300 K rows are detector context.\n")

    md.append("\n## Convergence\n")
    for sysname in ("cdte", "hgte"):
        for kind in ("ecut", "ecutrho", "kgrid"):
            md.append(f"### {sysname} {kind}\n" + conv_table(sysname, kind))

    md.append("\n## Production band edges\n")
    for sysname in ("cdte", "hgte"):
        md.append(f"### {sysname}\n" + band_table(sysname))

    md.append("\n## Hg0.8Cd0.2Te alloy (SQS, x=0.20)\n")
    alloy_rows = []
    for d in sorted((ROOT / "calculations/hgcdte").glob("sqs40_seed*_scf_*")):
        rj = d / "result.json"
        if not rj.exists():
            continue
        r = json.loads(rj.read_text())
        if not r["pw"]["ok"]:
            continue
        alloy_rows.append((d.name, r))
    if alloy_rows:
        md.append("| run | soc | E_tot (Ry) | E_F (eV) | HO (eV) | LU (eV) | grid gap proxy (eV) |")
        md.append("|---|---|---|---|---|---|---|")
        for name, r in alloy_rows:
            pw = r["pw"]
            md.append(
                f"| {name} | {r['soc']} | {_f(pw['total_energy_ry'])} "
                f"| {_f(pw['fermi_ev'])} | {_f(pw['highest_occupied_ev'])} "
                f"| {_f(pw['lowest_unoccupied_ev'])} | {_f(pw['gap_ev'])} |")
        eg0 = hansen_eg(0.2, 0.0)
        md.append(f"\nEmpirical reference (x=0.20): Eg(T=0K) = {eg0:.6f} eV, "
                  f"Eg(77K) = {hansen_eg(0.2, 77.0):.6f} eV, "
                  f"Eg(300K) = {hansen_eg(0.2, 300.0):.6f} eV "
                  "(EMPIRICAL; DFT compares against T=0K only).")
    else:
        md.append("_alloy runs pending_")

    (ROOT / "reports/results.md").write_text("\n".join(md) + "\n")
    print("wrote reports/results.md")
    return 0


if __name__ == "__main__":
    main()
